controller_frequency: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true

TrajectoryPlannerROS:
   max_vel_x: 0.2
   min_vel_x: 0.05
   max_vel_theta: 1.0
   min_vel_theta: 0.5
   max_rotational_vel: 1.0
   min_in_place_vel_theta: 0.5
   escape_vel: -0.1
   acc_lim_th: 0.75
   acc_lim_x: 0.50
   acc_lim_y: 0.50

   holonomic_robot: false
   yaw_goal_tolerance: 0.2 # about 11 degrees
   xy_goal_tolerance: 0.1  # 10 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 0.9996
   gdist_scale: 0.5
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.1
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 1.0
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 8
   vtheta_samples: 20
   dwa: true
   simple_attractor: false
